version: 0.2

phases:
  post_build:
    commands:
      - echo "Syncing files to S3"
      - aws s3 sync . s3://challengeproject --delete --exclude "*" --include "index.html

artifacts:
  files:
    - '**/*'
  base-directory: '.'
